name: Cypress E2E Tests

on:
   - push


jobs:
   test:
      name: Cypress run
      runs-on: ubuntu-20.04
      strategy:
         fail-fast: false
         matrix:
            containers: [1,2,3,4]

      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Cypress run
           uses: cypress-io/github-actions@v2
           with:
              record: true
              parallel: true
              browser: 'chrome'
              group: 'E2E Tests'
           env:
              REACT_APP_DHIS2_BASE_URL: ${{ secrets.REACT_APP_DHIS2_BASE_URL }}
              CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              CYPRESS_DHIS2_BASE_URL: ${{ secrets.CYPRESS_DHIS2_BASE_URL}}
              CYPRESS_DHIS2_USERNAME: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
              CYPRESS_DHIS2_PASSWORD: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

